### ISSUE TITLE
If configs.params.server.rootpath is used, the path is duplicated after local Login

### ISSUE THREAD

**Issue by simonprewo** [argoproj/argo-helm#3139]
### Describe the bug

Let say you want to run Argo under myhostname.com/argocd. "/argocd" is than configured in parameter `configs.params.server.rootpath: /argocd` . However, local login is distroyed afterwards because you argocd in the URL is duplicated.

The full configuration looks like that:

```yaml
configs:
  cm:
    url: myhostname.com/argocd
  params:
    server.rootpath: "/argocd"
server:
  ingress:
    enabled: true
```

### Related helm chart

argo-cd

### Helm chart version

7.7.16

### To Reproduce

1) Open `myhostname.com/argocd`
2) My URL is changed/forwarded to `myhostname.com/argocd/login?return_url=https%3A%2F%2Fmyhostname.com%2Fargocd%2Fapplications`
3) I login locally using my admin account
4) After succsessful Login, I got redirected to `myhostname.com/argocd/argocd/applications`
5) If I remove one argocd everythings works fine  `myhostname.com/argocd/applications`

### Expected behavior

After Login page `myhostname.com/argocd/applications` is opened. (No duplicate argocd)

**Comment by eric-young** [comment]
Me as well

**Comment by gustavo-sdo** [comment]
I am also experiencing the same issue.
Since version **7.7.0** of the Helm Chart, this problem has occurred.
I am currently using version **7.6.12**, and this bug does not occur after authentication in that version.

This is preventing me from updating to the latest version of the project.

**Comment by xheladinish** [comment]
Same issue here. Any ETA. This is happening for me while trying to set up Ingress using the ALB Load balancer on a specific path.

**Comment by ashmulik** [comment]
I am facing the same exact issue. Any idea when there will be a fix for that?

**Comment by unmerkbar** [comment]
Same for me. Looking forward to see a fix.

**Comment by pramodasahoo** [comment]
Hi,
I have same problem. I am using helmchart deploy

Deployed Chart version: 7.8.22
Deployed App version: v2.14.9

in 2.14.9 version, Since the login phase is ok, after that the root path is duplicated.

server.basehref: /argocd
server.rootpath: '/argocd'

but it's redirecting after login https://localhost/argocd/argocd/applications

**Comment by rossifumax** [comment]
Hello,

It's fixed in v2.14.10 of ArgoCD ! 🎉 
Please use Helm chart version v7.8.26 to fix it 🙂 

Enjoy !

**Comment by hostalp** [comment]
It looks like the issue is back in a different form.
I can open the login page, perform login and use the web app.
But the logout action redirects to the server root (https://servername" instead of https://servername/argocd or so):
\> `GET https://servername/argocd/auth/logout`
< `HTTP/2 303`
< `location: https://servername`

`values.yaml`:
```yaml
configs:
  params:
    server.basehref: &rootPath /argocd
    server.rootpath: *rootPath

server:
  ingress:
    enabled: true
    path: *rootPath

  ingressGrpc:
    enabled: true
    path: *rootPath

notifications:
  argocdUrl: "https://servername/argocd"
```
I think I set it everywhere I could (using YAML anchors to simplify the configuration). Or am I missing something?

Also when I use DEX server for LDAP authentication (which I had to add to the Ingress resource manually by the way), it redirects me to `/auth/callback` instead of `/argocd/auth/callback` after logging in.

EDIT: I noticed that there's `url` parameter without the `/argocd` in its value in the `argocd-cm` confirmap, so I added
```
configs:
  cm:
    url: https://servername/argocd
```
to values.yaml which got it to work, but this isn't documented so I consider it as workaround only as I'd expect the value to be constructed on deployment from params such as `global.domain`, `configs.params.server.rootpath` etc.
This parametes is also mentioned by the creator of this issue, however because it's undocumented I didn't initially use it.

Helm Chart argo-cd-8.1.2
Argo CD v3.0.6
